### ISSUE TITLE
Content-Encoding on S3 assets doesn't consult assets.gzip

### ISSUE THREAD

**Issue by tim-evans** [LevelbossMike/ember-deploy-s3#10]
We just got burned by this. :/

It seems like the code that adds `Content-Encoding: gzip` to files doesn't look at what the `gzip` property is on the config:

https://github.com/LevelbossMike/ember-deploy-s3/blob/master/lib/s3.js#L64-L67

**Comment by LevelbossMike** [comment]
Can you please provide a config that reproduces the issue?

Are you specifying `gzip: false` and s3 is still tagging the default extensions `[js, css, svg]` as gzipped content?

**Comment by tim-evans** [comment]
Yes

**Comment by tim-evans** [comment]
``` javascript
module.exports = {
  staging: {
    assets: {
      type: 's3',
      gzip: false,
      gzipExtensions: ['js', 'css', 'svg'],
      accessKeyId: 'AWS_ACCESS_KEY_ID',
      secretAccessKey: 'AWS_SECRET_KEY',
      bucket: 'my-app-staging'
    }
  }
};
```
