### ISSUE TITLE
Dist Prefix inside S3 Bucket

### ISSUE THREAD

**Issue by hhff** [LevelbossMike/ember-deploy-s3#13]
Hi @LevelbossMike !  Thankyou so much for the hard work here.  Just getting started on using it now!

I usually use https://github.com/tedconf/ember-cli-front-end-builds for Ember deployment, and with that system you can pass a `distPrefix`, so that all of the dists are stored seperately.

ie
/bucket/dist-sha
/bucket/dist-sha2

is this possible with Ember Deploy S3?

Thankyou!

**Comment by LevelbossMike** [comment]
No this isn't supported in this addon unfortunately. But the new 0.5-release of ember-cli-deploy will make stuff like this easy.

**Comment by hhff** [comment]
okies~!
