### ISSUE TITLE
Unable to sync: CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by ashrafhasson** [LevelbossMike/ember-deploy-s3#16]
When I try to run `ember deploy --environment production` on my laptop, it works fine, when I try to run the same code checked out on a different machine which has the same ember-cli@0.2.7 and node@0.12.1 it fails with the following error:

``` js
Built project successfully. Stored in "tmp/deploy-dist/".
Uploading assets...
Unable to sync: CredentialsError: Missing credentials in config
    at Object.parse (native)
    at /home/devops/alnahtha-fe/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/metadata_service.js:97:38
    at IncomingMessage.<anonymous> (/home/devops/alnahtha-fe/node_modules/ember-deploy-s3/node_modules/s3/node_modules/aws-sdk/lib/metadata_service.js:72:43)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

I found that downgrading or upgrading node has no effect. I've double checked deploy.js credentials and even installed awscli (which shouldn't matter, the way I understand it)

**Comment by LevelbossMike** [comment]
I am using this addon with different machines and it works fine. Are you using dotenv for your key-management? Maybe you are just missing the correct environment settings.

**Comment by ashrafhasson** [comment]
@LevelbossMike I think I was running out of memory which was causing a few things to get dropped (or not picked up). This error went away when I ran with a bit more memory!
Thanks for your response though and thanks for the great addon :)

**Comment by ashrafhasson** [comment]
Sorry @LevelbossMike this came back to haunt me on my Mac (with plenty of RAM), I'm getting the following:

``` js
Unable to sync: CredentialsError: Missing credentials in config
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:300:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

basically, process.env['AWS_ACCESS_KEY'] appears to be undefined and I don't think I'm using a dotenv for key management, since I don't know what that precisely is :D
I've followed the ember-cli-deploy config example and configured the AWS_ACCESS_KEY in config/environment.js under ENV.
Mind you, this works just fine on my Linux machine! I've just cloned the project git to my Mac and the issue resurfaced. Appreciate any hints.

**Comment by LevelbossMike** [comment]
@ashrafhasson ember-cli-deploy isn't reading settings out of `environment.js` as this is used for configuration of your app and not your deployment. Configuration of your deployment is done in `deploy.js`

The `process.env`in the example section for `deploy.js` references an environment variable set on your machine. I assume you have set an environment variable called AWS_ACCESS_KEY on your linux machine but not on your mac.

Hope that helps. If that doesn't work for you feel free to write me a message on the ember slack channel. You can find me via my github handle there as well.

**Comment by ashrafhasson** [comment]
makes sense, thanks
