### ISSUE TITLE
Configuration for 3rd party S3 clone

### ISSUE THREAD

**Issue by sokratisg** [LevelbossMike/ember-deploy-s3#2]
Hello!

Is there any way to configure ember-deploy-s3 to deploy assets on other 3rd party AWS S3 clones such as Ceph?

Ceph has full compatibility with AWS S3 so I believe it would be nice to test this functionality.

Thanks!

**Comment by LevelbossMike** [comment]
Hi! sorry for not reaching back out sooner.

This definitely sounds like a great idea. I have not used Ceph myself but it would be great if you can try to use the library with Ceph and report back any issues you are experiencing. If the API is compatible I see no reason why this should not work as of today.
