### ISSUE TITLE
PROPOSAL - Do not set cache header for uploaded index.html on S3

### ISSUE THREAD

**Issue by rtablada** [LevelbossMike/ember-deploy-s3#6]
While I understand the project's focus on versioned deploys, but this is actually quite usable in a scenario to simply upload the full site (including index.html) to a flat file service.

When this is the use case, the 2 year cache header on the index.html file means that serving completely from S3 isn't practical since people will only get updates if the break cache (losing benefits of unchanged assets).

**Comment by LevelbossMike** [comment]
When you decide to deploy to s3 as an index store there's the https://github.com/Kerry350/ember-deploy-s3-index project for that.

You are right that the 2 year cache header does not make much sense and this should be removed. But as I said I strongly recommend the s3-index-adapter if you want to serve the index.html from s3.
