### ISSUE TITLE
Hangs on Uploading assets

### ISSUE THREAD

**Issue by tehmaestro** [LevelbossMike/ember-deploy-s3#8]
Hi. It seems that the deployment hangs on Uploading assets. Nothing happens .. anybody had any similar issues?

Thanks.

EDIT: It worked eventually, it just took a bit.

**Comment by kdawgwilk** [comment]
@tehmaestro I am running into the same issue, how long did it take for yours to finish?

**Comment by Matt-Jensen** [comment]
A really long time...
